AWSTemplateFormatVersion: "2010-09-09"
Resources:
    GetUserDetailsByIDLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            FunctionName: "getUserDetailsByID-CFN"
            Handler: "lambda_function.lambda_handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: "dalvacationhomeassets"
                S3Key: "getUserDetailsByID.zip"
            MemorySize: 128
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
            Runtime: "python3.12"
            Timeout: 3
            EphemeralStorage: 
                Size: 512
    LambdaURL:
        Type: AWS::Lambda::Url
        Properties:
          AuthType: NONE
          Cors: 
              AllowCredentials: false
              AllowHeaders: 
                - Content-Type
              AllowMethods: 
                - GET
              AllowOrigins: 
                - "*"
          InvokeMode: BUFFERED
          TargetFunctionArn: !GetAtt GetUserDetailsByIDLambda.Arn
    PermissionURLInvokeGetUserDetailsByID:
        Type: AWS::Lambda::Permission
        Properties:
          FunctionName: !Ref GetUserDetailsByIDLambda
          FunctionUrlAuthType: 'NONE'
          Action: lambda:InvokeFunctionUrl
          Principal: '*'